# main.py
import hashlib
import json
import re
import threading
import time
import uuid

from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from fastapi import FastAPI, HTTPException, Form, BackgroundTasks, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from sldl_runner import parse_track_list, run_sldl

BASE_DIR = Path(__file__).parent
CONFIG_PATH = BASE_DIR / "config.json"
SOULSEEK_CONF_PATH = BASE_DIR / "sockseek.conf"
STATIC_DIR = BASE_DIR / "static"

app = FastAPI(title="VK -> Soulseek Downloader")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

STATIC_DIR.mkdir(exist_ok=True)
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

jobs: Dict[str, Dict] = {}


#
# CONFIG
#

def load_config() -> Dict:
    if CONFIG_PATH.exists():
        try:
            return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def save_config(cfg: Dict) -> None:
    CONFIG_PATH.write_text(
        json.dumps(cfg, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def write_sockseek_conf(username: str, password: str, output_dir: str) -> None:
    content = f"""# Generated by setup - do not edit manually
username = {username}
password = {password}
pref-format = flac,mp3
pref-min-bitrate = 320
pref-strict-title = true
pref-strict-artist = true
pref-strict-album = true
pref-length-tol = 5
output-dir = {output_dir}
"""
    SOULSEEK_CONF_PATH.write_text(content, encoding="utf-8")


def is_configured() -> bool:
    cfg = load_config()
    return bool(cfg.get("configured")) and SOULSEEK_CONF_PATH.exists()


#
# FOLDER NAME
#

def sanitize_folder_name(name: str) -> str:
    name = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name)
    name = name.strip().rstrip(".")
    return name[:120] if name else "sockseek_job"


def derive_folder_name(tracks: List[Dict], playlist_name: Optional[str] = None) -> str:
    if playlist_name and playlist_name.strip():
        return sanitize_folder_name(playlist_name.strip())
    albums = [t.get("album", "").strip() for t in tracks if t.get("album", "").strip()]
    if albums:
        most_common, _ = Counter(albums).most_common(1)[0]
        return sanitize_folder_name(most_common)
    if tracks:
        first = tracks[0]
        return sanitize_folder_name(f"{first['artist']} - {first['title']}")
    return "sockseek_job"


#
# EXTENSION BRIDGE
#

_extension_inbox: Dict[str, Dict] = {}
_extension_results: Dict[str, Dict] = {}
_extension_lock = threading.Lock()
_extension_last_seen = {"t": 0.0}


@app.get("/api/extension/inbox")
async def extension_inbox():
    _extension_last_seen["t"] = time.time()
    with _extension_lock:
        if _extension_inbox:
            cmd_id = next(iter(_extension_inbox))
            return JSONResponse(_extension_inbox.pop(cmd_id))
    return JSONResponse({})


@app.post("/api/extension/result")
async def extension_result(payload: dict):
    cmd_id = payload.get("id")
    if not cmd_id:
        raise HTTPException(status_code=400, detail="Missing id")
    with _extension_lock:
        _extension_results[cmd_id] = payload.get("result")
    return JSONResponse({"ok": True})


@app.get("/api/extension/status")
async def extension_status():
    delta = time.time() - _extension_last_seen["t"]
    return JSONResponse({
        "alive": delta < 15,
        "last_seen_seconds": round(delta, 1),
    })


@app.post("/api/vk-command")
async def vk_command(playlist_url: str = Form(...)):
    if not playlist_url.strip():
        raise HTTPException(status_code=400, detail="Missing playlist URL")
    cmd_id = str(uuid.uuid4())
    with _extension_lock:
        _extension_inbox[cmd_id] = {
            "id": cmd_id,
            "action": "extractPlaylist",
            "playlistUrl": playlist_url.strip(),
        }
    return JSONResponse({"command_id": cmd_id})


@app.get("/api/vk-command/{command_id}")
async def vk_command_status(command_id: str):
    with _extension_lock:
        if command_id in _extension_results:
            return JSONResponse({
                "status": "done",
                "result": _extension_results.pop(command_id),
            })
    return JSONResponse({"status": "pending"})


#
# SETUP
#

@app.get("/setup", response_class=HTMLResponse)
async def setup_page():
    if is_configured():
        return RedirectResponse(url="/")
    html = (BASE_DIR / "setup.html").read_text(encoding="utf-8")
    return HTMLResponse(content=html)


@app.post("/api/setup")
async def do_setup(
    soulseek_username: str = Form(...),
    soulseek_password: str = Form(...),
    output_dir: str = Form(""),
):
    soulseek_username = soulseek_username.strip()
    soulseek_password = soulseek_password.strip()
    output_dir = output_dir.strip() or str(BASE_DIR / "downloads")

    if not soulseek_username or not soulseek_password:
        raise HTTPException(status_code=400, detail="Username and password are required")

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    write_sockseek_conf(soulseek_username, soulseek_password, output_dir)

    save_config({
        "configured": True,
        "soulseek_username": soulseek_username,
        "output_dir": output_dir,
        "configured_at": datetime.now().isoformat(),
    })

    return JSONResponse({"success": True})


@app.get("/api/config")
async def get_config():
    cfg = load_config()
    return JSONResponse({
        "configured": is_configured(),
        "soulseek_username": cfg.get("soulseek_username", ""),
        "output_dir": cfg.get("output_dir", ""),
    })


@app.post("/api/config/reset")
async def reset_config():
    if CONFIG_PATH.exists():
        CONFIG_PATH.unlink()
    if SOULSEEK_CONF_PATH.exists():
        SOULSEEK_CONF_PATH.unlink()
    return JSONResponse({"success": True})


#
# MAIN UI
#

@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    if not is_configured():
        return RedirectResponse(url="/setup")
    html = (BASE_DIR / "index.html").read_text(encoding="utf-8")
    return HTMLResponse(content=html)


#
# DOWNLOAD
#

# `SongJob: downloading: <track>: <seeder>\<path>`
RE_DOWNLOADING = re.compile(
    r'SongJob:\s+downloading:\s+(.+?):\s+([^\\]+)\\(.+)$'
)
# `SongJob: succeeded: <track>: <seeder>\<path>`
RE_SUCCESS = re.compile(
    r'SongJob:\s+succeeded:\s+(.+?):\s+([^\\]+)\\'
)
# `SongJob: failed [reason]: <track>` or `SongJob: download attempt failed: <track>: <seeder>\...`
RE_FAILED = re.compile(
    r'SongJob:\s+(?:download attempt failed|failed\s*\[[^\]]*\]):\s+(.+?)(?::|$)'
)


@app.post("/api/download")
async def download(
    background_tasks: BackgroundTasks,
    track_list: str = Form(...),
    album_mode: bool = Form(False),
    playlist_name: str = Form(""),
):
    tracks = parse_track_list(track_list)
    if not tracks:
        raise HTTPException(status_code=400, detail="No tracks parsed from list")

    cfg = load_config()
    output_dir = cfg.get("output_dir", str(BASE_DIR / "downloads"))
    folder_name = derive_folder_name(tracks, playlist_name)

    job_id = hashlib.md5(f"{datetime.now().isoformat()}".encode()).hexdigest()[:12]
    jobs[job_id] = {
        "id": job_id,
        "status": "starting",
        "total": len(tracks),
        "downloaded": 0,
        "failed": 0,
        "progress": 0.0,
        "message": f"Queued {len(tracks)} tracks",
        "created": datetime.now().isoformat(),
        "album_mode": album_mode,
        "folder_name": folder_name,
        "output_dir": output_dir,
        "log": [],
        "tracks": tracks,
        "leechers": {},
        "counted_tracks": [],
        "browse_entries": [],
        "browse_index": {},
    }

    def progress_cb(current: int, total: int, message: str = ""):
        jobs[job_id]["downloaded"] = current
        jobs[job_id]["progress"] = current / max(total, 1)
        jobs[job_id]["message"] = message or f"({current}/{total}) downloading"

    def log_cb(line: str):
        job = jobs[job_id]
        job["log"].append(line)
        if len(job["log"]) > 500:
            job["log"] = job["log"][-500:]

        # Live feed: file just started downloading
        dm = RE_DOWNLOADING.search(line)
        if dm:
            track_key = dm.group(1).strip()
            username = dm.group(2).strip()
            filepath = dm.group(3).strip()
            key = f"{track_key}|{username}"
            if key not in job["browse_index"]:
                idx = len(job["browse_entries"])
                job["browse_index"][key] = idx
                job["browse_entries"].append({
                    "track": track_key,
                    "seeder": username,
                    "path": filepath,
                    "state": "active",
                })

        # Live feed: file completed
        sm = RE_SUCCESS.search(line)
        if sm:
            track_key = sm.group(1).strip()
            username = sm.group(2).strip()
            key = f"{track_key}|{username}"
            if key in job["browse_index"]:
                idx = job["browse_index"][key]
                job["browse_entries"][idx]["state"] = "done"

            # Seeder counter, dedup by (track, seeder)
            if key not in job["counted_tracks"]:
                job["counted_tracks"].append(key)
                job["leechers"][username] = job["leechers"].get(username, 0) + 1

        # Live feed: mark as failed only if there is no success for the pair
        fm = RE_FAILED.search(line)
        if fm:
            track_key = fm.group(1).strip()
            # We don't know which seeder failed from this line alone,
            # so just record it against the first active entry for this track.
            for entry in job["browse_entries"]:
                if entry["track"] == track_key and entry["state"] == "active":
                    entry["state"] = "failed"
                    break

    async def run():
        try:
            jobs[job_id]["status"] = "running"
            jobs[job_id]["message"] = "Starting download..."

            result = await run_sldl(
                tracks=tracks,
                job_id=job_id,
                folder_name=folder_name,
                output_dir=output_dir,
                album_mode=album_mode,
                progress_cb=progress_cb,
                log_cb=log_cb,
            )

            if result["exit_code"] == 0:
                status = "complete"
            elif result["downloaded"] > 0:
                status = "partial"
            else:
                status = "error"

            jobs[job_id].update({
                "status": status,
                "downloaded": result["downloaded"],
                "failed": result["failed"],
                "progress": 1.0,
                "message": (
                    f"Done - {result['downloaded']} downloaded, "
                    f"{result['failed']} failed (exit {result['exit_code']})"
                ),
                "log_path": result.get("log_path"),
                "finished_at": datetime.now().isoformat(),
            })
        except Exception as e:
            import traceback
            tb = traceback.format_exc()
            jobs[job_id]["status"] = "error"
            jobs[job_id]["message"] = str(e)
            jobs[job_id]["log"].append(f"ERROR: {e}")
            jobs[job_id]["log"].append(tb)
            print(f"[Job {job_id}] ERROR: {e}\n{tb}")

    background_tasks.add_task(run)
    return JSONResponse({"job_id": job_id, "total": len(tracks)})


@app.get("/api/jobs")
async def get_jobs():
    return JSONResponse({"jobs": jobs})


@app.get("/api/jobs/{job_id}")
async def get_job(job_id: str):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    return JSONResponse(jobs[job_id])


@app.get("/api/jobs/{job_id}/log")
async def get_job_log(job_id: str):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    job = jobs[job_id]
    log_path = job.get("log_path")
    if log_path and Path(log_path).exists():
        text = Path(log_path).read_text(encoding="utf-8", errors="replace")
        return JSONResponse({"log": text, "source": "file"})
    return JSONResponse({"log": "\n".join(job.get("log", [])), "source": "memory"})


if __name__ == "__main__":
    import uvicorn
    print("\n" + "=" * 60)
    print("VK -> Soulseek Downloader")
    print("=" * 60)
    print("")
    print(f"  Config: {CONFIG_PATH}")
    print(f"  Soulseek conf: {SOULSEEK_CONF_PATH}")
    print("")
    print("  Server: http://127.0.0.1:8000")
    print("=" * 60 + "\n")
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)